export const REQUEST = 'REQUEST'
export const SUCCESS = 'SUCCESS'
export const FAILURE = 'FAILURE'

export const FETCH_BOOKS = 'FETCH_BOOKS_'

export const ADD_BOOK_TO_CART = 'ADD_BOOK_TO_CART'
export const REMOVE_BOOK_FROM_CART = 'REMOVE_BOOK_FROM_CART'
export const INCREASE_CART_COUNT = 'INCREASE_BOOK_COUNT_CART'
export const DECREASE_CART_COUNT = 'DECREASE_BOOK_COUNT_CART'

export const ADD_ITEM_TO_WISHLIST = 'ADD_ITEM_TO_WISHLIST'
export const REMOVE_ITEM_FROM_WISHLIST = 'REMOVE_ITEM_FROM_WISHLIST'
